version: "3.3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: pg_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bot_vk_sergey
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: api_sergey
    build: ./myapp
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bot_vk_sergey
      - DB_HOST=db
      - PORT=5000
      - NODE_ENV=development
    volumes:
      - .:/myapp
      - /myapp/node_modules
    ports:
      - 5000:5000
    command: npm run start
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:1.11
    ports:
      - 8000:8000
    volumes:
      - ./nginx/proxy/prod.conf:/etc/nginx/conf.d/prod.conf:ro
      - /var/www/front:/app/static/front
#      - /var/www/memory_book_ADMIN/build:/app/static/adminFront
#      - /home/images:/persist_media
    depends_on:
      - api
    restart: always

volumes:
  pg_data:
networks:
  ms_network:
    external: true